/*Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with  and , the first  terms will be: 1, 2, 3, 5, 8, 13, 21 ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million,
  find the sum of the even-valued terms*/

let num1 = 1;
let num2 = 2;
let sum = num2;

while(num2 <= 4000000)
{
    let temp = num2;
    num1 = num2;
    num2 = temp + num2;

    if(num2 %2 == 0)
    {
        sum += num2
    }

}

console.log("The sum of even valued in fib sequence is: " + sum);